import * as Linking from 'expo-linking';
import { supabase } from './supabase';

// Trip invite codes (0010_trip_invites.sql). Admins create and share them;
// registering requires one (checked in the database's new-user trigger).

export type Invite = {
  code: string;
  label: string | null;
  created_at: string;
  expires_at: string | null;
  max_uses: number | null;
  uses: number;
  revoked_at: string | null;
};

export const INVITE_PATTERN = /^[A-Z0-9]{4}-[A-Z0-9]{4}$/;

/** "k7qm2xpa", " K7QM-2XPA " → "K7QM-2XPA" (or the cleaned text if it isn't one yet). */
export function normalizeInvite(raw: string): string {
  const s = raw.toUpperCase().replace(/[^A-Z0-9]/g, '');
  return s.length === 8 ? `${s.slice(0, 4)}-${s.slice(4)}` : raw.trim().toUpperCase();
}

export function isActive(i: Invite, now = Date.now()): boolean {
  if (i.revoked_at) return false;
  if (i.expires_at && new Date(i.expires_at).getTime() <= now) return false;
  if (i.max_uses !== null && i.uses >= i.max_uses) return false;
  return true;
}

export async function fetchInvites(): Promise<Invite[]> {
  const { data, error } = await supabase
    .from('trip_invites')
    .select('code, label, created_at, expires_at, max_uses, uses, revoked_at')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return data ?? [];
}

/** Creates a code (generated by the database). `days` = valid for that many days. */
export async function createInvite(
  userId: string,
  opts: { label?: string; maxUses?: number | null; days?: number | null },
): Promise<Invite> {
  const { data, error } = await supabase
    .from('trip_invites')
    .insert({
      created_by: userId,
      label: opts.label?.trim() || null,
      max_uses: opts.maxUses ?? null,
      expires_at: opts.days ? new Date(Date.now() + opts.days * 86_400_000).toISOString() : null,
    })
    .select('code, label, created_at, expires_at, max_uses, uses, revoked_at')
    .single();
  if (error) throw error;
  return data;
}

export async function revokeInvite(code: string): Promise<void> {
  const { error } = await supabase.from('trip_invites').update({ revoked_at: new Date().toISOString() }).eq('code', code);
  if (error) throw error;
}

/**
 * Link that opens registration with the code filled in. With a web address
 * configured (EXPO_PUBLIC_SITE_URL, e.g. the Vercel site) it works for anyone,
 * app or not; otherwise it's the app's own link.
 */
export function inviteLink(code: string): string {
  const site = process.env.EXPO_PUBLIC_SITE_URL?.replace(/\/+$/, '');
  if (site) return `${site}/register?invite=${encodeURIComponent(code)}`;
  return Linking.createURL('/register', { queryParams: { invite: code } });
}

export function inviteMessage(code: string): string {
  return (
    `You're invited to Epic Asia, our trip app for Japan, China and Hong Kong (June 5 – 19, 2027).\n\n` +
    `Your invite code: ${code}\n` +
    `Join here: ${inviteLink(code)}`
  );
}

/** Supabase hides the trigger's message; a rejected code surfaces as this generic error. */
export function isInviteRejection(message: string): boolean {
  return /database error saving new user|invalid_invite_code/i.test(message);
}
