// Generated by tools/build-yuki-knowledge.mjs from the app's bundled content — do not edit.
// Run `npm run build:yuki` after changing src/lib/arrivals.ts, places.ts or phrases.ts.
export const KNOWLEDGE = {
  "checked": "October 2026",
  "passport": "US passports",
  "legs": [
    {
      "key": "tokyo",
      "city": "Tokyo",
      "country": "Japan",
      "dates": "Jun 7 – 11",
      "from": "2027-06-06"
    },
    {
      "key": "kyoto",
      "city": "Kyoto & Nara",
      "country": "Japan",
      "dates": "Jun 11 – 12",
      "from": "2027-06-11"
    },
    {
      "key": "beijing",
      "city": "Beijing",
      "country": "China",
      "dates": "Jun 12 – 15",
      "from": "2027-06-12"
    },
    {
      "key": "shanghai",
      "city": "Shanghai",
      "country": "China",
      "dates": "Jun 15 – 18",
      "from": "2027-06-15"
    },
    {
      "key": "hongKong",
      "city": "Hong Kong",
      "country": "China",
      "dates": "Jun 18 – 20",
      "from": "2027-06-18"
    }
  ],
  "countries": [
    {
      "key": "japan",
      "name": "Japan",
      "dates": "Jun 6 – 12",
      "entry": "No visa needed for a tourist stay of up to 90 days.",
      "visa": [
        "US passport holders can visit visa-free for up to 90 days as tourists.",
        "Your passport must be valid for your whole stay. Have your onward flight (to Beijing) ready to show."
      ],
      "forms": [
        "Visit Japan Web: register your passport, flight and customs declaration before you fly. It gives you QR codes for immigration and customs, so you skip the paper forms.",
        "Screenshot the QR codes and add them to My documents — airport Wi-Fi can be slow."
      ],
      "tips": [
        "Get a transit IC card (Suica or PASMO, or add Suica to Apple Wallet) for trains, buses and convenience stores.",
        "Cash is still common: 7-Eleven ATMs take foreign cards."
      ],
      "links": [
        {
          "label": "Visit Japan Web",
          "url": "https://www.vjw.digital.go.jp/"
        },
        {
          "label": "Japan visa exemptions (Ministry of Foreign Affairs)",
          "url": "https://www.mofa.go.jp/j_info/visit/visa/short/novisa.html"
        },
        {
          "label": "US State Dept: Japan",
          "url": "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Japan.html"
        }
      ],
      "airports": [
        "NRT",
        "KIX"
      ]
    },
    {
      "key": "china",
      "name": "Mainland China",
      "dates": "Jun 12 – 18",
      "entry": "Visa-free transit may cover this leg; otherwise you need a tourist (L) visa. Decide early.",
      "visa": [
        "Option 1 — 240-hour visa-free transit: available to US citizens flying from one country or region to a different one through China. Japan → China → Hong Kong counts, because Hong Kong is a separate region for this rule. You must hold a confirmed onward ticket out of mainland China within 240 hours (10 days), enter at an eligible port (Beijing and Shanghai airports are), and stay within the permitted areas (Beijing and Shanghai both are).",
        "At immigration, go to the counter for visa-free transit and show your onward ticket to Hong Kong.",
        "Option 2 — tourist (L) visa: apply through the Chinese Visa Application Service Center weeks ahead. Choose this if anyone in your group doesn’t meet the transit rules, or if the rules change.",
        "Passports should have at least 6 months’ validity and blank pages."
      ],
      "forms": [
        "Arrival card: fill it in on the plane or at the airport (an online version is also offered). Keep your passport on you — hotels register every guest with the police."
      ],
      "tips": [
        "Set up Alipay or WeChat Pay with a foreign card before you go — most shops and taxis expect it.",
        "Google, WhatsApp and Instagram are blocked in mainland China. Roaming data from your home carrier, or a travel eSIM, usually still reaches them.",
        "Download offline maps and translation before you land."
      ],
      "links": [
        {
          "label": "National Immigration Administration (visa-free transit)",
          "url": "https://en.nia.gov.cn/"
        },
        {
          "label": "Chinese Visa Application Service Center",
          "url": "https://www.visaforchina.cn/"
        },
        {
          "label": "US State Dept: China",
          "url": "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/China.html"
        }
      ],
      "airports": [
        "PEK",
        "PVG"
      ]
    },
    {
      "key": "hongKong",
      "name": "Hong Kong",
      "dates": "Jun 18 – 20",
      "entry": "No visa needed for a visit of up to 90 days.",
      "visa": [
        "US passport holders can visit visa-free for up to 90 days.",
        "Hong Kong has its own immigration, separate from mainland China — you pass through it even when arriving from Shanghai."
      ],
      "forms": [
        "No arrival form. Immigration gives you a small landing slip — keep it with your passport until you leave."
      ],
      "tips": [
        "Get an Octopus card (or add it to Apple Wallet) for the MTR, buses, ferries and shops.",
        "Google, WhatsApp and Instagram work normally again here."
      ],
      "links": [
        {
          "label": "Hong Kong Immigration Department",
          "url": "https://www.immd.gov.hk/eng/"
        },
        {
          "label": "US State Dept: Hong Kong",
          "url": "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/HongKong.html"
        }
      ],
      "airports": [
        "HKG"
      ]
    }
  ],
  "airports": [
    {
      "code": "NRT",
      "name": "Narita International",
      "city": "Tokyo",
      "country": "japan",
      "role": "Arrive in Japan",
      "arrive": [
        "Follow the yellow Arrivals (到着) signs from the gate.",
        "Immigration: take the Foreign Passports lanes. Show the Visit Japan Web immigration QR, then fingerprints and a photo.",
        "Baggage claim: find your flight’s carousel on the screens.",
        "Customs: scan the Visit Japan Web customs QR at the e-gates (or hand in the paper declaration).",
        "Arrivals lobby: train ticket counters, bus counters and the taxi rank are all on this level."
      ],
      "toCity": [
        "Narita Express (N’EX) — direct to Tokyo, Shinagawa and Shinjuku stations, about 1 hour.",
        "Keisei Skyliner — to Ueno and Nippori, about 45 minutes.",
        "Airport Limousine Bus — to many central hotels, 75–120 minutes depending on traffic."
      ],
      "mapLink": "https://www.narita-airport.jp/en/"
    },
    {
      "code": "KIX",
      "name": "Kansai International",
      "city": "Osaka (for Kyoto & Nara)",
      "country": "japan",
      "role": "Leave Japan for Beijing",
      "depart": [
        "Arrive 2½–3 hours before an international flight.",
        "Check in at your airline’s counter (Terminal 1 for most full-service airlines; check your booking).",
        "Security, then departure immigration — the automated gates are fastest.",
        "Use up your yen before immigration; change leftovers airside if you need to."
      ],
      "toCity": [
        "From Kyoto: JR Haruka limited express to Kansai Airport, about 75–80 minutes."
      ],
      "mapLink": "https://www.kansai-airport.or.jp/en/"
    },
    {
      "code": "PEK",
      "name": "Beijing Capital International",
      "city": "Beijing",
      "country": "china",
      "role": "Arrive in China",
      "arrive": [
        "Follow the Arrivals (到达) signs from the gate.",
        "Have your completed arrival card, passport and onward ticket to Hong Kong ready.",
        "Immigration: using visa-free transit? Go to the counter marked for visa-free / 240-hour transit. With a visa, use the Foreigners lanes. Fingerprints are taken.",
        "Baggage claim, then customs: green channel if you have nothing to declare.",
        "Arrivals hall: change a little cash or use Alipay/WeChat Pay from here on."
      ],
      "toCity": [
        "Airport Express train — to Dongzhimen and Sanyuanqiao for the subway, about 20–30 minutes.",
        "Taxi — only from the official taxi rank; use DiDi in Alipay if you prefer an app."
      ],
      "mapLink": "https://en.bcia.com.cn/"
    },
    {
      "code": "PVG",
      "name": "Shanghai Pudong International",
      "city": "Shanghai",
      "country": "china",
      "role": "Leave mainland China for Hong Kong",
      "depart": [
        "Arrive 2½–3 hours early: departures to Hong Kong go through China’s exit immigration.",
        "Check in, then exit immigration (passport and boarding pass), then security.",
        "On visa-free transit? Leaving within the 240 hours is the rule — don’t miss this flight."
      ],
      "toCity": [
        "Maglev train — to Longyang Road, about 8 minutes, then the subway.",
        "Metro Line 2 — direct into the city, about 1 hour."
      ],
      "mapLink": "https://www.shanghaiairport.com/en/"
    },
    {
      "code": "HKG",
      "name": "Hong Kong International",
      "city": "Hong Kong",
      "country": "hongKong",
      "role": "Arrive in Hong Kong; fly home",
      "arrive": [
        "Follow the Arrival signs from the gate (there may be a short train ride).",
        "Immigration: Visitors lanes. You get a landing slip — keep it.",
        "Baggage claim, then customs: green channel if you have nothing to declare.",
        "Arrival hall: Airport Express ticket desks and the Octopus counter are right there."
      ],
      "depart": [
        "Flying home on a participating airline? In-town check-in at Hong Kong or Kowloon station lets you drop bags in the city on the way.",
        "Arrive 2½–3 hours early; departure immigration has e-Channel gates for visitors."
      ],
      "toCity": [
        "Airport Express — to Kowloon and Hong Kong stations, about 25 minutes, with free shuttle buses to many hotels.",
        "Taxis — red taxis go to Kowloon and Hong Kong Island."
      ],
      "mapLink": "https://www.hongkongairport.com/en/"
    }
  ],
  "checklist": [
    "Passport valid 6+ months past the trip, with blank pages",
    "China: decide visa-free transit or an L visa (and apply if needed)",
    "Japan: complete Visit Japan Web and save the QR codes",
    "Travel insurance, with the policy saved in My documents",
    "Alipay or WeChat Pay set up with a foreign card",
    "Tell your bank and card company where you’re going",
    "Phone plan or eSIM that roams in Japan, China and Hong Kong",
    "Re-check the entry rules 4–6 weeks before flying"
  ],
  "weatherCities": [
    {
      "key": "tokyo",
      "name": "Tokyo",
      "lat": 35.6812,
      "lng": 139.7671,
      "typicalJune": {
        "hi": 26,
        "lo": 19,
        "note": "Rainy season (tsuyu) — humid, umbrella days"
      }
    },
    {
      "key": "kyoto",
      "name": "Kyoto & Nara",
      "lat": 35.0116,
      "lng": 135.7681,
      "typicalJune": {
        "hi": 28,
        "lo": 20,
        "note": "Rainy season — warm and humid"
      }
    },
    {
      "key": "beijing",
      "name": "Beijing",
      "lat": 39.9042,
      "lng": 116.4074,
      "typicalJune": {
        "hi": 31,
        "lo": 20,
        "note": "Hot and mostly dry — sun hat and water"
      }
    },
    {
      "key": "shanghai",
      "name": "Shanghai",
      "lat": 31.2304,
      "lng": 121.4737,
      "typicalJune": {
        "hi": 28,
        "lo": 21,
        "note": "Plum rains (meiyu) — muggy, frequent showers"
      }
    },
    {
      "key": "hongKong",
      "name": "Hong Kong",
      "lat": 22.3193,
      "lng": 114.1694,
      "typicalJune": {
        "hi": 31,
        "lo": 27,
        "note": "Hot, very humid, heavy showers; typhoon season starts"
      }
    }
  ],
  "phrasebook": {
    "Basics": [
      {
        "en": "Hello",
        "japanese": "こんにちは (konnichiwa)",
        "mandarin": "你好 (nǐ hǎo)",
        "cantonese": "你好 (nei5 hou2)"
      },
      {
        "en": "Good morning",
        "japanese": "おはようございます (ohayō gozaimasu)",
        "mandarin": "早上好 (zǎoshang hǎo)",
        "cantonese": "早晨 (zou2 san4)"
      },
      {
        "en": "Thank you",
        "japanese": "ありがとうございます (arigatō gozaimasu)",
        "mandarin": "谢谢 (xièxie)",
        "cantonese": "唔該 (m4 goi1)"
      },
      {
        "en": "Excuse me / sorry",
        "japanese": "すみません (sumimasen)",
        "mandarin": "不好意思 (bù hǎo yìsi)",
        "cantonese": "唔好意思 (m4 hou2 ji3 si1)"
      },
      {
        "en": "Yes",
        "japanese": "はい (hai)",
        "mandarin": "是的 (shì de)",
        "cantonese": "係 (hai6)"
      },
      {
        "en": "No",
        "japanese": "いいえ (iie)",
        "mandarin": "不是 (bú shì)",
        "cantonese": "唔係 (m4 hai6)"
      },
      {
        "en": "Please (when asking for something)",
        "japanese": "お願いします (onegaishimasu)",
        "mandarin": "请 (qǐng)",
        "cantonese": "唔該 (m4 goi1)"
      },
      {
        "en": "Do you speak English?",
        "japanese": "英語を話せますか？ (eigo o hanasemasu ka?)",
        "mandarin": "你会说英语吗？ (nǐ huì shuō yīngyǔ ma?)",
        "cantonese": "你識唔識講英文？ (nei5 sik1 m4 sik1 gong2 jing1 man2?)"
      },
      {
        "en": "I don’t understand",
        "japanese": "わかりません (wakarimasen)",
        "mandarin": "我听不懂 (wǒ tīng bù dǒng)",
        "cantonese": "我唔明 (ngo5 m4 ming4)"
      },
      {
        "en": "Could you take a photo of us?",
        "japanese": "写真を撮っていただけますか？ (shashin o totte itadakemasu ka?)",
        "mandarin": "可以帮我们拍张照吗？ (kěyǐ bāng wǒmen pāi zhāng zhào ma?)",
        "cantonese": "可唔可以幫我哋影張相？ (ho2 m4 ho2 ji5 bong1 ngo5 dei6 jing2 zoeng1 soeng2?)"
      },
      {
        "en": "Goodbye",
        "japanese": "さようなら (sayōnara)",
        "mandarin": "再见 (zàijiàn)",
        "cantonese": "拜拜 (baai1 baai3)"
      }
    ],
    "Getting around": [
      {
        "en": "Where is the toilet?",
        "japanese": "トイレはどこですか？ (toire wa doko desu ka?)",
        "mandarin": "洗手间在哪里？ (xǐshǒujiān zài nǎlǐ?)",
        "cantonese": "洗手間喺邊度？ (sai2 sau2 gaan1 hai2 bin1 dou6?)"
      },
      {
        "en": "Where is the station?",
        "japanese": "駅はどこですか？ (eki wa doko desu ka?)",
        "mandarin": "地铁站在哪里？ (dìtiě zhàn zài nǎlǐ?)",
        "cantonese": "港鐵站喺邊度？ (gong2 tit3 zaam6 hai2 bin1 dou6?)"
      },
      {
        "en": "Where is the exit?",
        "japanese": "出口はどこですか？ (deguchi wa doko desu ka?)",
        "mandarin": "出口在哪里？ (chūkǒu zài nǎlǐ?)",
        "cantonese": "出口喺邊度？ (ceot1 hau2 hai2 bin1 dou6?)"
      },
      {
        "en": "Please take me to this address",
        "japanese": "この住所までお願いします (kono jūsho made onegaishimasu)",
        "mandarin": "请带我去这个地址 (qǐng dài wǒ qù zhège dìzhǐ)",
        "cantonese": "唔該去呢個地址 (m4 goi1 heoi3 ni1 go3 dei6 zi2)"
      },
      {
        "en": "Please stop here",
        "japanese": "ここで止めてください (koko de tomete kudasai)",
        "mandarin": "请在这里停 (qǐng zài zhèlǐ tíng)",
        "cantonese": "唔該呢度停 (m4 goi1 ni1 dou6 ting4)"
      },
      {
        "en": "I’m lost",
        "japanese": "道に迷いました (michi ni mayoimashita)",
        "mandarin": "我迷路了 (wǒ mílù le)",
        "cantonese": "我蕩失路 (ngo5 dong6 sat1 lou6)"
      }
    ],
    "Food & drink": [
      {
        "en": "This one, please",
        "japanese": "これをください (kore o kudasai)",
        "mandarin": "我要这个 (wǒ yào zhège)",
        "cantonese": "唔該，我要呢個 (m4 goi1, ngo5 jiu3 ni1 go3)"
      },
      {
        "en": "Water, please",
        "japanese": "お水をください (omizu o kudasai)",
        "mandarin": "请给我一杯水 (qǐng gěi wǒ yì bēi shuǐ)",
        "cantonese": "唔該畀杯水我 (m4 goi1 bei2 bui1 seoi2 ngo5)"
      },
      {
        "en": "The bill, please",
        "japanese": "お会計お願いします (okaikei onegaishimasu)",
        "mandarin": "买单 (mǎidān)",
        "cantonese": "唔該埋單 (m4 goi1 maai4 daan1)"
      },
      {
        "en": "Not spicy, please",
        "japanese": "辛くしないでください (karaku shinaide kudasai)",
        "mandarin": "不要辣 (bú yào là)",
        "cantonese": "唔要辣 (m4 jiu3 laat6)"
      },
      {
        "en": "I’m vegetarian",
        "japanese": "ベジタリアンです (bejitarian desu)",
        "mandarin": "我吃素 (wǒ chī sù)",
        "cantonese": "我食齋 (ngo5 sik6 zaai1)"
      },
      {
        "en": "I’m allergic to nuts",
        "japanese": "ナッツアレルギーがあります (nattsu arerugī ga arimasu)",
        "mandarin": "我对坚果过敏 (wǒ duì jiānguǒ guòmǐn)",
        "cantonese": "我對果仁敏感 (ngo5 deoi3 gwo2 jan4 man5 gam2)"
      },
      {
        "en": "Delicious!",
        "japanese": "おいしい！ (oishii!)",
        "mandarin": "好吃！ (hǎochī!)",
        "cantonese": "好好食！ (hou2 hou2 sik6!)"
      }
    ],
    "Shopping": [
      {
        "en": "How much is this?",
        "japanese": "これはいくらですか？ (kore wa ikura desu ka?)",
        "mandarin": "这个多少钱？ (zhège duōshao qián?)",
        "cantonese": "呢個幾多錢？ (ni1 go3 gei2 do1 cin2?)"
      },
      {
        "en": "Can I pay by card?",
        "japanese": "カードで払えますか？ (kādo de haraemasu ka?)",
        "mandarin": "可以刷卡吗？ (kěyǐ shuākǎ ma?)",
        "cantonese": "可唔可以碌卡？ (ho2 m4 ho2 ji5 luk1 kaat1?)"
      },
      {
        "en": "Can I pay with my phone?",
        "japanese": "スマホで払えますか？ (sumaho de haraemasu ka?)",
        "mandarin": "可以用支付宝吗？ (kěyǐ yòng Zhīfùbǎo ma?)",
        "cantonese": "可唔可以用八達通？ (ho2 m4 ho2 ji5 jung6 baat3 daat6 tung1?)"
      },
      {
        "en": "Can it be a bit cheaper?",
        "japanese": "少し安くなりますか？ (sukoshi yasuku narimasu ka?)",
        "mandarin": "可以便宜一点吗？ (kěyǐ piányi yìdiǎn ma?)",
        "cantonese": "可唔可以平啲？ (ho2 m4 ho2 ji5 peng4 di1?)"
      },
      {
        "en": "Just looking, thanks",
        "japanese": "見ているだけです (mite iru dake desu)",
        "mandarin": "我只是看看 (wǒ zhǐshì kànkan)",
        "cantonese": "我睇吓啫 (ngo5 tai2 haa5 ze1)"
      }
    ],
    "Help": [
      {
        "en": "Help!",
        "japanese": "助けて！ (tasukete!)",
        "mandarin": "救命！ (jiùmìng!)",
        "cantonese": "救命！ (gau3 meng6!)"
      },
      {
        "en": "Please call a doctor",
        "japanese": "医者を呼んでください (isha o yonde kudasai)",
        "mandarin": "请叫医生 (qǐng jiào yīshēng)",
        "cantonese": "唔該叫醫生 (m4 goi1 giu3 ji1 sang1)"
      },
      {
        "en": "Please call an ambulance",
        "japanese": "救急車を呼んでください (kyūkyūsha o yonde kudasai)",
        "mandarin": "请叫救护车 (qǐng jiào jiùhùchē)",
        "cantonese": "唔該叫白車 (m4 goi1 giu3 baak6 ce1)"
      },
      {
        "en": "Please call the police",
        "japanese": "警察を呼んでください (keisatsu o yonde kudasai)",
        "mandarin": "请叫警察 (qǐng jiào jǐngchá)",
        "cantonese": "唔該報警 (m4 goi1 bou3 ging2)"
      },
      {
        "en": "Where is a pharmacy?",
        "japanese": "薬局はどこですか？ (yakkyoku wa doko desu ka?)",
        "mandarin": "药店在哪里？ (yàodiàn zài nǎlǐ?)",
        "cantonese": "藥房喺邊度？ (joek6 fong4 hai2 bin1 dou6?)"
      }
    ]
  },
  "emergency": {
    "Japan (Japanese)": "Police 110 · Ambulance & fire 119",
    "Mainland China (Mandarin)": "Police 110 · Ambulance 120 · Fire 119",
    "Hong Kong (Cantonese)": "Police, ambulance & fire 999"
  }
} as const;
