// Generated by tools/build-yuki-knowledge.mjs from the app's bundled content — do not edit.
// Run `npm run build:yuki` after changing src/lib/arrivals.ts, places.ts or phrases.ts.
export const KNOWLEDGE = {
  "checked": "October 2026",
  "passport": "US passports",
  "legs": [
    {
      "key": "tokyo",
      "city": "Tokyo",
      "country": "Japan",
      "dates": "Jun 6 – 9",
      "from": "2027-06-05"
    },
    {
      "key": "kyoto",
      "city": "Kyoto & Nara",
      "country": "Japan",
      "dates": "Jun 9 – 11",
      "from": "2027-06-09"
    },
    {
      "key": "beijing",
      "city": "Beijing",
      "country": "China",
      "dates": "Jun 11 – 14",
      "from": "2027-06-11"
    },
    {
      "key": "shanghai",
      "city": "Shanghai",
      "country": "China",
      "dates": "Jun 14 – 17",
      "from": "2027-06-14"
    },
    {
      "key": "hongKong",
      "city": "Hong Kong",
      "country": "China",
      "dates": "Jun 17 – 19",
      "from": "2027-06-17"
    }
  ],
  "countries": [
    {
      "key": "japan",
      "name": "Japan",
      "dates": "Jun 5 – 11",
      "entry": "No visa needed for a tourist stay of up to 90 days.",
      "visa": [
        "US passport holders can visit visa-free for up to 90 days as tourists.",
        "Your passport must be valid for your whole stay. Have your onward flight (to Beijing) ready to show."
      ],
      "forms": [
        "Visit Japan Web: register your passport, flight and customs declaration before you fly. It gives you QR codes for immigration and customs, so you skip the paper forms.",
        "Screenshot the QR codes and add them to My documents — airport Wi-Fi can be slow."
      ],
      "tips": [
        "Get a transit IC card (Suica or PASMO, or add Suica to Apple Wallet) for trains, buses and convenience stores.",
        "Cash is still common: 7-Eleven ATMs take foreign cards."
      ],
      "links": [
        {
          "label": "Visit Japan Web",
          "url": "https://www.vjw.digital.go.jp/"
        },
        {
          "label": "Japan visa exemptions (Ministry of Foreign Affairs)",
          "url": "https://www.mofa.go.jp/j_info/visit/visa/short/novisa.html"
        },
        {
          "label": "US State Dept: Japan",
          "url": "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/Japan.html"
        }
      ],
      "airports": [
        "NRT",
        "KIX"
      ]
    },
    {
      "key": "china",
      "name": "Mainland China",
      "dates": "Jun 11 – 17",
      "entry": "Visa-free transit may cover this leg; otherwise you need a tourist (L) visa. Decide early.",
      "visa": [
        "Option 1 — 240-hour visa-free transit: available to US citizens flying from one country or region to a different one through China. Japan → China → Hong Kong counts, because Hong Kong is a separate region for this rule. You must hold a confirmed onward ticket out of mainland China within 240 hours (10 days), enter at an eligible port (Beijing and Shanghai airports are), and stay within the permitted areas (Beijing and Shanghai both are).",
        "At immigration, go to the counter for visa-free transit and show your onward ticket to Hong Kong.",
        "Option 2 — tourist (L) visa: apply through the Chinese Visa Application Service Center weeks ahead. Choose this if anyone in your group doesn’t meet the transit rules, or if the rules change.",
        "Passports should have at least 6 months’ validity and blank pages."
      ],
      "forms": [
        "Arrival card: fill it in on the plane or at the airport (an online version is also offered). Keep your passport on you — hotels register every guest with the police."
      ],
      "tips": [
        "Set up Alipay or WeChat Pay with a foreign card before you go — most shops and taxis expect it.",
        "Google, WhatsApp and Instagram are blocked in mainland China. Roaming data from your home carrier, or a travel eSIM, usually still reaches them.",
        "Download offline maps and translation before you land."
      ],
      "links": [
        {
          "label": "National Immigration Administration (visa-free transit)",
          "url": "https://en.nia.gov.cn/"
        },
        {
          "label": "Chinese Visa Application Service Center",
          "url": "https://www.visaforchina.cn/"
        },
        {
          "label": "US State Dept: China",
          "url": "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/China.html"
        }
      ],
      "airports": [
        "PEK",
        "PVG"
      ]
    },
    {
      "key": "hongKong",
      "name": "Hong Kong",
      "dates": "Jun 17 – 19",
      "entry": "No visa needed for a visit of up to 90 days.",
      "visa": [
        "US passport holders can visit visa-free for up to 90 days.",
        "Hong Kong has its own immigration, separate from mainland China — you pass through it even when arriving from Shanghai."
      ],
      "forms": [
        "No arrival form. Immigration gives you a small landing slip — keep it with your passport until you leave."
      ],
      "tips": [
        "Get an Octopus card (or add it to Apple Wallet) for the MTR, buses, ferries and shops.",
        "Google, WhatsApp and Instagram work normally again here."
      ],
      "links": [
        {
          "label": "Hong Kong Immigration Department",
          "url": "https://www.immd.gov.hk/eng/"
        },
        {
          "label": "US State Dept: Hong Kong",
          "url": "https://travel.state.gov/content/travel/en/international-travel/International-Travel-Country-Information-Pages/HongKong.html"
        }
      ],
      "airports": [
        "HKG"
      ]
    }
  ],
  "airports": [
    {
      "code": "NRT",
      "name": "Narita International",
      "city": "Tokyo",
      "country": "japan",
      "role": "Arrive in Japan",
      "arrive": [
        "Follow the yellow Arrivals (到着) signs from the gate.",
        "Immigration: take the Foreign Passports lanes. Show the Visit Japan Web immigration QR, then fingerprints and a photo.",
        "Baggage claim: find your flight’s carousel on the screens.",
        "Customs: scan the Visit Japan Web customs QR at the e-gates (or hand in the paper declaration).",
        "Arrivals lobby: train ticket counters, bus counters and the taxi rank are all on this level."
      ],
      "toCity": [
        "Narita Express (N’EX) — direct to Tokyo, Shinagawa and Shinjuku stations, about 1 hour.",
        "Keisei Skyliner — to Ueno and Nippori, about 45 minutes.",
        "Airport Limousine Bus — to many central hotels, 75–120 minutes depending on traffic."
      ],
      "mapLink": "https://www.narita-airport.jp/en/"
    },
    {
      "code": "KIX",
      "name": "Kansai International",
      "city": "Osaka (for Kyoto & Nara)",
      "country": "japan",
      "role": "Leave Japan for Beijing",
      "depart": [
        "Arrive 2½–3 hours before an international flight.",
        "Check in at your airline’s counter (Terminal 1 for most full-service airlines; check your booking).",
        "Security, then departure immigration — the automated gates are fastest.",
        "Use up your yen before immigration; change leftovers airside if you need to."
      ],
      "toCity": [
        "From Kyoto: JR Haruka limited express to Kansai Airport, about 75–80 minutes."
      ],
      "mapLink": "https://www.kansai-airport.or.jp/en/"
    },
    {
      "code": "PEK",
      "name": "Beijing Capital International",
      "city": "Beijing",
      "country": "china",
      "role": "Arrive in China",
      "arrive": [
        "Follow the Arrivals (到达) signs from the gate.",
        "Have your completed arrival card, passport and onward ticket to Hong Kong ready.",
        "Immigration: using visa-free transit? Go to the counter marked for visa-free / 240-hour transit. With a visa, use the Foreigners lanes. Fingerprints are taken.",
        "Baggage claim, then customs: green channel if you have nothing to declare.",
        "Arrivals hall: change a little cash or use Alipay/WeChat Pay from here on."
      ],
      "toCity": [
        "Airport Express train — to Dongzhimen and Sanyuanqiao for the subway, about 20–30 minutes.",
        "Taxi — only from the official taxi rank; use DiDi in Alipay if you prefer an app."
      ],
      "mapLink": "https://en.bcia.com.cn/"
    },
    {
      "code": "PVG",
      "name": "Shanghai Pudong International",
      "city": "Shanghai",
      "country": "china",
      "role": "Leave mainland China for Hong Kong",
      "depart": [
        "Arrive 2½–3 hours early: departures to Hong Kong go through China’s exit immigration.",
        "Check in, then exit immigration (passport and boarding pass), then security.",
        "On visa-free transit? Leaving within the 240 hours is the rule — don’t miss this flight."
      ],
      "toCity": [
        "Maglev train — to Longyang Road, about 8 minutes, then the subway.",
        "Metro Line 2 — direct into the city, about 1 hour."
      ],
      "mapLink": "https://www.shanghaiairport.com/en/"
    },
    {
      "code": "HKG",
      "name": "Hong Kong International",
      "city": "Hong Kong",
      "country": "hongKong",
      "role": "Arrive in Hong Kong; fly home",
      "arrive": [
        "Follow the Arrival signs from the gate (there may be a short train ride).",
        "Immigration: Visitors lanes. You get a landing slip — keep it.",
        "Baggage claim, then customs: green channel if you have nothing to declare.",
        "Arrival hall: Airport Express ticket desks and the Octopus counter are right there."
      ],
      "depart": [
        "Flying home on a participating airline? In-town check-in at Hong Kong or Kowloon station lets you drop bags in the city on the way.",
        "Arrive 2½–3 hours early; departure immigration has e-Channel gates for visitors."
      ],
      "toCity": [
        "Airport Express — to Kowloon and Hong Kong stations, about 25 minutes, with free shuttle buses to many hotels.",
        "Taxis — red taxis go to Kowloon and Hong Kong Island."
      ],
      "mapLink": "https://www.hongkongairport.com/en/"
    }
  ],
  "checklist": [
    "Passport valid 6+ months past the trip, with blank pages",
    "China: decide visa-free transit or an L visa (and apply if needed)",
    "Japan: complete Visit Japan Web and save the QR codes",
    "Travel insurance, with the policy saved in My documents",
    "Alipay or WeChat Pay set up with a foreign card",
    "Tell your bank and card company where you’re going",
    "Phone plan or eSIM that roams in Japan, China and Hong Kong",
    "Re-check the entry rules 4–6 weeks before flying"
  ],
  "weatherCities": [
    {
      "key": "tokyo",
      "name": "Tokyo",
      "lat": 35.6812,
      "lng": 139.7671,
      "typicalJune": {
        "hi": 26,
        "lo": 19,
        "note": "Rainy season (tsuyu) — humid, umbrella days"
      }
    },
    {
      "key": "kyoto",
      "name": "Kyoto & Nara",
      "lat": 35.0116,
      "lng": 135.7681,
      "typicalJune": {
        "hi": 28,
        "lo": 20,
        "note": "Rainy season — warm and humid"
      }
    },
    {
      "key": "beijing",
      "name": "Beijing",
      "lat": 39.9042,
      "lng": 116.4074,
      "typicalJune": {
        "hi": 31,
        "lo": 20,
        "note": "Hot and mostly dry — sun hat and water"
      }
    },
    {
      "key": "shanghai",
      "name": "Shanghai",
      "lat": 31.2304,
      "lng": 121.4737,
      "typicalJune": {
        "hi": 28,
        "lo": 21,
        "note": "Plum rains (meiyu) — muggy, frequent showers"
      }
    },
    {
      "key": "hongKong",
      "name": "Hong Kong",
      "lat": 22.3193,
      "lng": 114.1694,
      "typicalJune": {
        "hi": 31,
        "lo": 27,
        "note": "Hot, very humid, heavy showers; typhoon season starts"
      }
    }
  ],
  "emergency": {
    "Japan (Japanese)": "Police 110 · Ambulance & fire 119",
    "Mainland China (Mandarin)": "Police 110 · Ambulance 120 · Fire 119",
    "Hong Kong (Cantonese)": "Police, ambulance & fire 999"
  }
} as const;
