// Godzilla Rampage is one self-contained HTML file (canvas + inline JS):
// assets/games/rampage.html (art + code, like the other assets — its pixel
// palette is game art, outside the app's colour tokens). The app shows it in a WebView (native) or
// an iframe (web), so it needs the file as a string: this script writes
// src/games/rampage/html.ts from it, after syntax-checking the inline
// script (a typo would otherwise only show as a blank game on a phone).
//
//   node tools/build-rampage.mjs          # regenerate html.ts
//   node tools/build-rampage.mjs --check  # CI: fail if html.ts is stale or the script has a syntax error

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'assets/games/rampage.html');
const out = join(root, 'src/games/rampage/html.ts');

const html = readFileSync(src, 'utf8');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]);
if (!scripts.length) throw new Error('rampage.html has no inline <script>');
for (const code of scripts) new vm.Script(code, { filename: 'rampage.html' }); // throws on a syntax error

const ts =
  '// GENERATED by tools/build-rampage.mjs from rampage.html — do not edit.\n' +
  '// Edit assets/games/rampage.html, then run: node tools/build-rampage.mjs\n' +
  `const RAMPAGE_HTML: string = ${JSON.stringify(html)};\nexport default RAMPAGE_HTML;\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    // missing counts as stale
  }
  if (current !== ts) {
    console.error('src/games/rampage/html.ts is out of date — run: node tools/build-rampage.mjs');
    process.exit(1);
  }
  console.log('rampage: html.ts is up to date');
} else {
  writeFileSync(out, ts);
  console.log(`rampage: wrote ${out} (${Math.round(ts.length / 1024)} KB)`);
}
