// Godzilla Rampage is a self-contained HTML game: assets/games/rampage/
// index.html (page + controls) plus ES modules (game.js logic, render3d.js
// three.js voxel scene, models.js / voxel.js art, hud.js overlay). The app
// shows it in a WebView (native) or an iframe (web), offline, so it needs one
// HTML string: this script bundles the modules with esbuild (three.js tree-
// shaken and minified in), inlines the bundle into index.html and writes
// src/games/rampage/html.ts. Art is all code — the game's colours are game
// art, outside the app's colour tokens.
//
//   node tools/build-rampage.mjs          # regenerate html.ts
//   node tools/build-rampage.mjs --check  # CI: fail if html.ts is stale
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets/games/rampage');
const out = join(root, 'src/games/rampage/html.ts');

const result = await build({
  entryPoints: [join(dir, 'game.js')],
  bundle: true,
  format: 'iife',
  minify: true,
  target: ['safari15', 'chrome100'],
  legalComments: 'none',
  write: false,
  logLevel: 'silent',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
new vm.Script(js, { filename: 'rampage-bundle.js' }); // throws on a syntax error

const shell = readFileSync(join(dir, 'index.html'), 'utf8');
if (!shell.includes('/*GAME*/') || !shell.includes('/*INIT*/null')) throw new Error('index.html is missing a placeholder');
const html = shell.replace('/*GAME*/', () => js);

const ts =
  '// GENERATED by tools/build-rampage.mjs from assets/games/rampage/ — do not edit.\n' +
  '// Edit the files there, then run: npm run build:rampage\n' +
  `const RAMPAGE_HTML: string = ${JSON.stringify(html)};\nexport default RAMPAGE_HTML;\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    // missing counts as stale
  }
  if (current !== ts) {
    console.error('src/games/rampage/html.ts is out of date — run: npm run build:rampage');
    process.exit(1);
  }
  console.log('rampage: html.ts is up to date');
} else {
  writeFileSync(out, ts);
  console.log(`rampage: wrote ${out} (${Math.round(ts.length / 1024)} KB)`);
}
