// The arcade games are self-contained HTML games: assets/games/<game>/
// index.html (page + controls) plus ES modules (game.js logic, three.js voxel
// scene, art, HUD overlay; shared art can be imported across games). The app
// shows each in a sandboxed iframe, offline, so each needs one HTML string:
// this script bundles the modules with esbuild (three.js tree-shaken and
// minified in), inlines the bundle into index.html and writes
// src/games/<game>/html.ts. Art is all code — the games' colours are game
// art, outside the app's colour tokens.
//
//   node tools/build-games.mjs          # regenerate every html.ts
//   node tools/build-games.mjs --check  # CI: fail if any html.ts is stale
import { build } from 'esbuild';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const GAMES = [
  { dir: 'rampage', name: 'RAMPAGE_HTML' },
  { dir: 'shinkansen', name: 'SHINKANSEN_HTML' },
];
const check = process.argv.includes('--check');
let stale = false;

for (const g of GAMES) {
  const dir = join(root, 'assets/games', g.dir);
  const out = join(root, 'src/games', g.dir, 'html.ts');
  const result = await build({
    entryPoints: [join(dir, 'game.js')],
    bundle: true,
    format: 'iife',
    minify: true,
    target: ['safari15', 'chrome100'],
    legalComments: 'none',
    write: false,
    logLevel: 'silent',
  });
  const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
  new vm.Script(js, { filename: `${g.dir}-bundle.js` }); // throws on a syntax error

  const shell = readFileSync(join(dir, 'index.html'), 'utf8');
  if (!shell.includes('/*GAME*/') || !shell.includes('/*INIT*/null')) throw new Error(`${g.dir}/index.html is missing a placeholder`);
  const html = shell.replace('/*GAME*/', () => js);
  const ts =
    `// GENERATED by tools/build-games.mjs from assets/games/${g.dir}/ — do not edit.\n` +
    '// Edit the files there, then run: npm run build:games\n' +
    `const ${g.name}: string = ${JSON.stringify(html)};\nexport default ${g.name};\n`;

  if (check) {
    let current = '';
    try {
      current = readFileSync(out, 'utf8');
    } catch {
      // missing counts as stale
    }
    if (current !== ts) {
      console.error(`src/games/${g.dir}/html.ts is out of date — run: npm run build:games`);
      stale = true;
    } else console.log(`${g.dir}: html.ts is up to date`);
  } else {
    mkdirSync(dirname(out), { recursive: true });
    writeFileSync(out, ts);
    console.log(`${g.dir}: wrote ${out} (${Math.round(ts.length / 1024)} KB)`);
  }
}
if (stale) process.exit(1);
